const keyData = {
  en: {
    'id-0': {
      'key-code': 'Backquote',
      display: '`',
      'display-code': '',
      'display-shift': '~',
      'display-shift-code': '',
    },
    'id-1': {
      'key-code': 'Digit1',
      display: '1',
      'display-code': '',
      'display-shift': '!',
      'display-shift-code': '',
    },
    'id-2': {
      'key-code': 'Digit2',
      display: '2',
      'display-code': '',
      'display-shift': '@',
      'display-shift-code': '',
    },
    'id-3': {
      'key-code': 'Digit3',
      display: '3',
      'display-code': '',
      'display-shift': '#',
      'display-shift-code': '',
    },
    'id-4': {
      'key-code': 'Digit4',
      display: '4',
      'display-code': '',
      'display-shift': '$',
      'display-shift-code': '',
    },
    'id-5': {
      'key-code': 'Digit5',
      display: '5',
      'display-code': '',
      'display-shift': '%',
      'display-shift-code': '',
    },
    'id-6': {
      'key-code': 'Digit6',
      display: '6',
      'display-code': '',
      'display-shift': '^',
      'display-shift-code': '',
    },
    'id-7': {
      'key-code': 'Digit7',
      display: '7',
      'display-code': '',
      'display-shift': '&',
      'display-shift-code': '',
    },
    'id-8': {
      'key-code': 'Digit8',
      display: '8',
      'display-code': '',
      'display-shift': '*',
      'display-shift-code': '',
    },
    'id-9': {
      'key-code': 'Digit9',
      display: '9',
      'display-code': '',
      'display-shift': '(',
      'display-shift-code': '',
    },
    'id-10': {
      'key-code': 'Digit0',
      display: '0',
      'display-code': '',
      'display-shift': ')',
      'display-shift-code': '',
    },
    'id-11': {
      'key-code': 'Minus',
      display: '-',
      'display-code': '',
      'display-shift': '_',
      'display-shift-code': '',
    },
    'id-12': {
      'key-code': 'Equal',
      display: '=',
      'display-code': '',
      'display-shift': '+',
      'display-shift-code': '',
    },
    'id-13': {
      'key-code': 'Backspace',
      display: '',
      'display-code': '',
      'display-shift': 'Backspace',
      'display-shift-code': '',
    },
    'id-14': {
      'key-code': 'Tab',
      display: '',
      'display-code': '',
      'display-shift': 'Tab',
      'display-shift-code': '',
    },
    'id-15': {
      'key-code': 'KeyQ',
      display: 'q',
      'display-code': '',
      'display-shift': 'Q',
      'display-shift-code': '',
    },
    'id-16': {
      'key-code': 'KeyW',
      display: 'w',
      'display-code': '',
      'display-shift': 'W',
      'display-shift-code': '',
    },
    'id-17': {
      'key-code': 'KeyE',
      display: 'e',
      'display-code': '',
      'display-shift': 'E',
      'display-shift-code': '',
    },
    'id-18': {
      'key-code': 'KeyR',
      display: 'r',
      'display-code': '',
      'display-shift': 'R',
      'display-shift-code': '',
    },
    'id-19': {
      'key-code': 'KeyT',
      display: 't',
      'display-code': '',
      'display-shift': 'T',
      'display-shift-code': '',
    },
    'id-20': {
      'key-code': 'KeyY',
      display: 'y',
      'display-code': '',
      'display-shift': 'Y',
      'display-shift-code': '',
    },
    'id-21': {
      'key-code': 'KeyU',
      display: 'u',
      'display-code': '',
      'display-shift': 'U',
      'display-shift-code': '',
    },
    'id-22': {
      'key-code': 'KeyI',
      display: 'i',
      'display-code': '',
      'display-shift': 'I',
      'display-shift-code': '',
    },
    'id-23': {
      'key-code': 'KeyO',
      display: 'o',
      'display-code': '',
      'display-shift': 'O',
      'display-shift-code': '',
    },
    'id-24': {
      'key-code': 'KeyP',
      display: 'p',
      'display-code': '',
      'display-shift': 'P',
      'display-shift-code': '',
    },
    'id-25': {
      'key-code': 'BracketLeft',
      display: '[',
      'display-code': '',
      'display-shift': '{',
      'display-shift-code': '',
    },
    'id-26': {
      'key-code': 'BracketRight',
      display: ']',
      'display-code': '',
      'display-shift': '}',
      'display-shift-code': '',
    },
    'id-27': {
      'key-code': 'Backslash',
      display: '\\',
      'display-code': '',
      'display-shift': '/',
      'display-shift-code': '',
    },
    'id-28': {
      'key-code': 'Delete',
      display: '',
      'display-code': '',
      'display-shift': 'Del',
      'display-shift-code': '',
    },
    'id-29': {
      'key-code': 'CapsLock',
      display: '',
      'display-code': '',
      'display-shift': 'Caps',
      'display-shift-code': '',
    },
    'id-30': {
      'key-code': 'KeyA',
      display: 'a',
      'display-code': '',
      'display-shift': 'A',
      'display-shift-code': '',
    },
    'id-31': {
      'key-code': 'KeyS',
      display: 's',
      'display-code': '',
      'display-shift': 'S',
      'display-shift-code': '',
    },
    'id-32': {
      'key-code': 'KeyD',
      display: 'd',
      'display-code': '',
      'display-shift': 'D',
      'display-shift-code': '',
    },
    'id-33': {
      'key-code': 'KeyF',
      display: 'f',
      'display-code': '',
      'display-shift': 'F',
      'display-shift-code': '',
    },
    'id-34': {
      'key-code': 'KeyG',
      display: 'g',
      'display-code': '',
      'display-shift': 'G',
      'display-shift-code': '',
    },
    'id-35': {
      'key-code': 'KeyH',
      display: 'h',
      'display-code': '',
      'display-shift': 'H',
      'display-shift-code': '',
    },
    'id-36': {
      'key-code': 'KeyJ',
      display: 'j',
      'display-code': '',
      'display-shift': 'J',
      'display-shift-code': '',
    },
    'id-37': {
      'key-code': 'KeyK',
      display: 'k',
      'display-code': '',
      'display-shift': 'K',
      'display-shift-code': '',
    },
    'id-38': {
      'key-code': 'KeyL',
      display: 'l',
      'display-code': '',
      'display-shift': 'L',
      'display-shift-code': '',
    },
    'id-39': {
      'key-code': 'Semicolon',
      display: ';',
      'display-code': '',
      'display-shift': ':',
      'display-shift-code': '',
    },
    'id-40': {
      'key-code': 'Quote',
      display: "'",
      'display-code': '',
      'display-shift': '"',
      'display-shift-code': '',
    },
    'id-41': {
      'key-code': 'Enter',
      display: '',
      'display-code': '',
      'display-shift': 'Enter',
      'display-shift-code': '',
    },
    'id-42': {
      'key-code': 'ShiftLeft',
      display: '',
      'display-code': '',
      'display-shift': 'Shift',
      'display-shift-code': '',
    },
    'id-43': {
      'key-code': 'IntlBackslash',
      display: '\\',
      'display-code': '',
      'display-shift': '|',
      'display-shift-code': '',
    },
    'id-44': {
      'key-code': 'KeyZ',
      display: 'z',
      'display-code': '',
      'display-shift': 'Z',
      'display-shift-code': '',
    },
    'id-45': {
      'key-code': 'KeyX',
      display: 'x',
      'display-code': '',
      'display-shift': 'X',
      'display-shift-code': '',
    },
    'id-46': {
      'key-code': 'KeyC',
      display: 'c',
      'display-code': '',
      'display-shift': 'C',
      'display-shift-code': '',
    },
    'id-47': {
      'key-code': 'KeyV',
      display: 'v',
      'display-code': '',
      'display-shift': 'V',
      'display-shift-code': '',
    },
    'id-48': {
      'key-code': 'KeyB',
      display: 'b',
      'display-code': '',
      'display-shift': 'B',
      'display-shift-code': '',
    },
    'id-49': {
      'key-code': 'KeyN',
      display: 'n',
      'display-code': '',
      'display-shift': 'N',
      'display-shift-code': '',
    },
    'id-50': {
      'key-code': 'KeyM',
      display: 'm',
      'display-code': '',
      'display-shift': 'M',
      'display-shift-code': '',
    },
    'id-51': {
      'key-code': 'Comma',
      display: ',',
      'display-code': '',
      'display-shift': '<',
      'display-shift-code': '',
    },
    'id-52': {
      'key-code': 'Period',
      display: '.',
      'display-code': '',
      'display-shift': '>',
      'display-shift-code': '',
    },
    'id-53': {
      'key-code': 'Slash',
      display: '/',
      'display-code': '',
      'display-shift': '?',
      'display-shift-code': '',
    },
    'id-54': {
      'key-code': 'ArrowUp',
      display: '↑',
      'display-code': '',
      'display-shift': '',
      'display-shift-code': '',
    },
    'id-55': {
      'key-code': 'ShiftRight',
      display: '',
      'display-code': '',
      'display-shift': 'Shift',
      'display-shift-code': '',
    },
    'id-56': {
      'key-code': 'ControlLeft',
      display: '',
      'display-code': '',
      'display-shift': 'Ctrl',
      'display-shift-code': '',
    },
    'id-57': {
      'key-code': 'MetaLeft',
      display: '',
      'display-code': '',
      'display-shift': 'Win',
      'display-shift-code': '',
    },
    'id-58': {
      'key-code': 'AltLeft',
      display: '',
      'display-code': '',
      'display-shift': 'Alt',
      'display-shift-code': '',
    },
    'id-59': {
      'key-code': 'Space',
      display: ' ',
      'display-code': '',
      'display-shift': '',
      'display-shift-code': '',
    },
    'id-60': {
      'key-code': 'AltRight',
      display: '',
      'display-code': '',
      'display-shift': 'Alt',
      'display-shift-code': '',
    },
    'id-61': {
      'key-code': 'ControlRight',
      display: '',
      'display-code': '',
      'display-shift': 'Ctrl',
      'display-shift-code': '',
    },
    'id-62': {
      'key-code': 'ArrowLeft',
      display: '←',
      'display-code': '',
      'display-shift': '',
      'display-shift-code': '',
    },
    'id-63': {
      'key-code': 'ArrowDown',
      display: '↓',
      'display-code': '',
      'display-shift': '',
      'display-shift-code': '',
    },
    'id-64': {
      'key-code': 'ArrowRight',
      display: '→',
      'display-code': '',
      'display-shift': '',
      'display-shift-code': '',
    },
  },
  ru: {
    'id-0': {
      'key-code': 'Backquote',
      display: 'ё',
      'display-code': '',
      'display-shift': 'Ё',
      'display-shift-code': '',
    },
    'id-1': {
      'key-code': 'Digit1',
      display: '1',
      'display-code': '',
      'display-shift': '!',
      'display-shift-code': '',
    },
    'id-2': {
      'key-code': 'Digit2',
      display: '2',
      'display-code': '',
      'display-shift': '"',
      'display-shift-code': '',
    },
    'id-3': {
      'key-code': 'Digit3',
      display: '3',
      'display-code': '',
      'display-shift': '№',
      'display-shift-code': '',
    },
    'id-4': {
      'key-code': 'Digit4',
      display: '4',
      'display-code': '',
      'display-shift': ';',
      'display-shift-code': '',
    },
    'id-5': {
      'key-code': 'Digit5',
      display: '5',
      'display-code': '',
      'display-shift': '%',
      'display-shift-code': '',
    },
    'id-6': {
      'key-code': 'Digit6',
      display: '6',
      'display-code': '',
      'display-shift': ':',
      'display-shift-code': '',
    },
    'id-7': {
      'key-code': 'Digit7',
      display: '7',
      'display-code': '',
      'display-shift': '?',
      'display-shift-code': '',
    },
    'id-8': {
      'key-code': 'Digit8',
      display: '8',
      'display-code': '',
      'display-shift': '*',
      'display-shift-code': '',
    },
    'id-9': {
      'key-code': 'Digit9',
      display: '9',
      'display-code': '',
      'display-shift': '(',
      'display-shift-code': '',
    },
    'id-10': {
      'key-code': 'Digit0',
      display: '0',
      'display-code': '',
      'display-shift': ')',
      'display-shift-code': '',
    },
    'id-11': {
      'key-code': 'Minus',
      display: '-',
      'display-code': '',
      'display-shift': '_',
      'display-shift-code': '',
    },
    'id-12': {
      'key-code': 'Equal',
      display: '=',
      'display-code': '',
      'display-shift': '+',
      'display-shift-code': '',
    },
    'id-13': {
      'key-code': 'Backspace',
      display: '',
      'display-code': '',
      'display-shift': 'Backspace',
      'display-shift-code': '',
    },
    'id-14': {
      'key-code': 'Tab',
      display: '',
      'display-code': '',
      'display-shift': 'Tab',
      'display-shift-code': '',
    },
    'id-15': {
      'key-code': 'KeyQ',
      display: 'й',
      'display-code': '',
      'display-shift': 'Й',
      'display-shift-code': '',
    },
    'id-16': {
      'key-code': 'KeyW',
      display: 'ц',
      'display-code': '',
      'display-shift': 'Ц',
      'display-shift-code': '',
    },
    'id-17': {
      'key-code': 'KeyE',
      display: 'у',
      'display-code': '',
      'display-shift': 'У',
      'display-shift-code': '',
    },
    'id-18': {
      'key-code': 'KeyR',
      display: 'к',
      'display-code': '',
      'display-shift': 'К',
      'display-shift-code': '',
    },
    'id-19': {
      'key-code': 'KeyT',
      display: 'е',
      'display-code': '',
      'display-shift': 'Е',
      'display-shift-code': '',
    },
    'id-20': {
      'key-code': 'KeyY',
      display: 'н',
      'display-code': '',
      'display-shift': 'Н',
      'display-shift-code': '',
    },
    'id-21': {
      'key-code': 'KeyU',
      display: 'г',
      'display-code': '',
      'display-shift': 'Г',
      'display-shift-code': '',
    },
    'id-22': {
      'key-code': 'KeyI',
      display: 'ш',
      'display-code': '',
      'display-shift': 'Ш',
      'display-shift-code': '',
    },
    'id-23': {
      'key-code': 'KeyO',
      display: 'щ',
      'display-code': '',
      'display-shift': 'Щ',
      'display-shift-code': '',
    },
    'id-24': {
      'key-code': 'KeyP',
      display: 'з',
      'display-code': '',
      'display-shift': 'З',
      'display-shift-code': '',
    },
    'id-25': {
      'key-code': 'BracketLeft',
      display: 'х',
      'display-code': '',
      'display-shift': 'Х',
      'display-shift-code': '',
    },
    'id-26': {
      'key-code': 'BracketRight',
      display: 'ъ',
      'display-code': '',
      'display-shift': 'Ъ',
      'display-shift-code': '',
    },
    'id-27': {
      'key-code': 'Backslash',
      display: '\\',
      'display-code': '',
      'display-shift': '/',
      'display-shift-code': '',
    },
    'id-28': {
      'key-code': 'Delete',
      display: '',
      'display-code': '',
      'display-shift': 'Del',
      'display-shift-code': '',
    },
    'id-29': {
      'key-code': 'CapsLock',
      display: '',
      'display-code': '',
      'display-shift': 'Caps',
      'display-shift-code': '',
    },
    'id-30': {
      'key-code': 'KeyA',
      display: 'ф',
      'display-code': '',
      'display-shift': 'Ф',
      'display-shift-code': '',
    },
    'id-31': {
      'key-code': 'KeyS',
      display: 'ы',
      'display-code': '',
      'display-shift': 'Ы',
      'display-shift-code': '',
    },
    'id-32': {
      'key-code': 'KeyD',
      display: 'в',
      'display-code': '',
      'display-shift': 'В',
      'display-shift-code': '',
    },
    'id-33': {
      'key-code': 'KeyF',
      display: 'а',
      'display-code': '',
      'display-shift': 'А',
      'display-shift-code': '',
    },
    'id-34': {
      'key-code': 'KeyG',
      display: 'п',
      'display-code': '',
      'display-shift': 'П',
      'display-shift-code': '',
    },
    'id-35': {
      'key-code': 'KeyH',
      display: 'р',
      'display-code': '',
      'display-shift': 'Р',
      'display-shift-code': '',
    },
    'id-36': {
      'key-code': 'KeyJ',
      display: 'о',
      'display-code': '',
      'display-shift': 'О',
      'display-shift-code': '',
    },
    'id-37': {
      'key-code': 'KeyK',
      display: 'л',
      'display-code': '',
      'display-shift': 'Л',
      'display-shift-code': '',
    },
    'id-38': {
      'key-code': 'KeyL',
      display: 'д',
      'display-code': '',
      'display-shift': 'Д',
      'display-shift-code': '',
    },
    'id-39': {
      'key-code': 'Semicolon',
      display: 'ж',
      'display-code': '',
      'display-shift': 'Ж',
      'display-shift-code': '',
    },
    'id-40': {
      'key-code': 'Quote',
      display: 'э',
      'display-code': '',
      'display-shift': 'Э',
      'display-shift-code': '',
    },
    'id-41': {
      'key-code': 'Enter',
      display: '',
      'display-code': '',
      'display-shift': 'Enter',
      'display-shift-code': '',
    },
    'id-42': {
      'key-code': 'ShiftLeft',
      display: '',
      'display-code': '',
      'display-shift': 'Shift',
      'display-shift-code': '',
    },
    'id-43': {
      'key-code': 'IntlBackslash',
      display: '\\',
      'display-code': '',
      'display-shift': '|',
      'display-shift-code': '',
    },
    'id-44': {
      'key-code': 'KeyZ',
      display: 'я',
      'display-code': '',
      'display-shift': 'Я',
      'display-shift-code': '',
    },
    'id-45': {
      'key-code': 'KeyX',
      display: 'ч',
      'display-code': '',
      'display-shift': 'Ч',
      'display-shift-code': '',
    },
    'id-46': {
      'key-code': 'KeyC',
      display: 'с',
      'display-code': '',
      'display-shift': 'С',
      'display-shift-code': '',
    },
    'id-47': {
      'key-code': 'KeyV',
      display: 'м',
      'display-code': '',
      'display-shift': 'М',
      'display-shift-code': '',
    },
    'id-48': {
      'key-code': 'KeyB',
      display: 'и',
      'display-code': '',
      'display-shift': 'И',
      'display-shift-code': '',
    },
    'id-49': {
      'key-code': 'KeyN',
      display: 'т',
      'display-code': '',
      'display-shift': 'Т',
      'display-shift-code': '',
    },
    'id-50': {
      'key-code': 'KeyM',
      display: 'ь',
      'display-code': '',
      'display-shift': 'Ь',
      'display-shift-code': '',
    },
    'id-51': {
      'key-code': 'Comma',
      display: 'б',
      'display-code': '',
      'display-shift': 'Б',
      'display-shift-code': '',
    },
    'id-52': {
      'key-code': 'Period',
      display: 'ю',
      'display-code': '',
      'display-shift': 'Ю',
      'display-shift-code': '',
    },
    'id-53': {
      'key-code': 'Slash',
      display: '.',
      'display-code': '',
      'display-shift': ',',
      'display-shift-code': '',
    },
    'id-54': {
      'key-code': 'ArrowUp',
      display: '↑',
      'display-code': '',
      'display-shift': '',
      'display-shift-code': '',
    },
    'id-55': {
      'key-code': 'ShiftRight',
      display: '',
      'display-code': '',
      'display-shift': 'Shift',
      'display-shift-code': '',
    },
    'id-56': {
      'key-code': 'ControlLeft',
      display: '',
      'display-code': '',
      'display-shift': 'Ctrl',
      'display-shift-code': '',
    },
    'id-57': {
      'key-code': 'MetaLeft',
      display: '',
      'display-code': '',
      'display-shift': 'Win',
      'display-shift-code': '',
    },
    'id-58': {
      'key-code': 'AltLeft',
      display: '',
      'display-code': '',
      'display-shift': 'Alt',
      'display-shift-code': '',
    },
    'id-59': {
      'key-code': 'Space',
      display: ' ',
      'display-code': '',
      'display-shift': '',
      'display-shift-code': '',
    },
    'id-60': {
      'key-code': 'AltRight',
      display: '',
      'display-code': '',
      'display-shift': 'Alt',
      'display-shift-code': '',
    },
    'id-61': {
      'key-code': 'ControlRight',
      display: '',
      'display-code': '',
      'display-shift': 'Ctrl',
      'display-shift-code': '',
    },
    'id-62': {
      'key-code': 'ArrowLeft',
      display: '←',
      'display-code': '',
      'display-shift': '',
      'display-shift-code': '',
    },
    'id-63': {
      'key-code': 'ArrowDown',
      display: '↓',
      'display-code': '',
      'display-shift': '',
      'display-shift-code': '',
    },
    'id-64': {
      'key-code': 'ArrowRight',
      display: '→',
      'display-code': '',
      'display-shift': '',
      'display-shift-code': '',
    },
  },
};

export default keyData;
